"""Bind persisted PUA tail rules to their verified scanner evidence."""

from __future__ import annotations

from typing import Any, Iterator, Mapping

from .v2_scan_worker_auth import scan_evidence_sha256

TailLocator = tuple[int, str, int, int, int]
ASCII_LOWERCASE = "abcdefghijklmnopqrstuvwxyz"
TAIL_PROFILE_PROOF_VERSION = 1


def tail_profile_issues(config: Mapping[str, Any], scan: Mapping[str, Any]) -> list[dict[str, str]]:
    """Return every configured alternate that is not an exact auto-proven scan result.

    The central service cannot open local desktop fonts.  Its durable proof is
    therefore the current, hash-bound Illustrator scan generated by the
    trusted local scanner.  A plain PUA number in a client-supplied config is
    not proof: it could point to a blank glyph or the ordinary base letter.
    """

    scanned_tails = dict(iter_contract_tails(scan))
    trusted_scan = _has_trusted_tail_profile_proof(scan)
    issues: list[dict[str, str]] = []
    for locator, tail, option, slot in _iter_contract_tail_contexts(config):
        if not _uses_tail_profile(tail):
            continue
        scanned = scanned_tails.get(locator)
        font_matches = _matches_tail_font_dependency(option, slot, scanned)
        profile_matches = (
            trusted_scan
            and _matches_auto_tail_scan(tail, scanned)
            and _has_full_coverage(scanned)
        )
        if profile_matches and font_matches:
            continue
        is_pua = _uses_pua(tail)
        issues.append({
            "path": tail_path(locator),
            "code": (
                "tail_font_dependency_unverified"
                if profile_matches and not font_matches
                else "tail_pua_profile_unverified" if is_pua else "tail_opentype_profile_unverified"
            ),
            "reason": (
                "尾巴字形档案只适用于扫描样本使用的唯一字体；请确认该槽位字体依赖与样本字体一致后重新扫描模板。"
                if profile_matches and not font_matches
                else "PUA 尾巴字形必须来自当前模板 AI 的完整字母表自动扫描证明；请重新扫描模板后再保存。"
                if is_pua
                else "OpenType 尾巴字形必须来自当前模板 AI 的完整字母表自动扫描证明；请重新扫描模板后再保存。"
            ),
        })
    return issues


def iter_contract_tails(value: Mapping[str, Any]) -> Iterator[tuple[TailLocator, dict[str, Any]]]:
    """Yield V2 contract-shaped tail records with an unambiguous locator."""

    for locator, tail, _, _ in _iter_contract_tail_contexts(value):
        yield locator, tail


def _iter_contract_tail_contexts(
    value: Mapping[str, Any],
) -> Iterator[tuple[TailLocator, dict[str, Any], Mapping[str, Any], Mapping[str, Any]]]:
    """Yield tails plus their option/slot context used by the renderer."""

    for output_index, output in enumerate(value.get("outputs", [])):
        if not isinstance(output, Mapping):
            continue
        for branch in ("design", "font"):
            section = output.get(branch)
            if not isinstance(section, Mapping):
                continue
            for option_index, option in enumerate(section.get("options", [])):
                if not isinstance(option, Mapping):
                    continue
                for slot_index, slot in enumerate(option.get("slots", [])):
                    if not isinstance(slot, Mapping):
                        continue
                    for tail_index, tail in enumerate(slot.get("tails", [])):
                        if isinstance(tail, Mapping):
                            yield (
                                (output_index, branch, option_index, slot_index, tail_index),
                                dict(tail),
                                option,
                                slot,
                            )


def tail_path(locator: TailLocator) -> str:
    output, branch, option, slot, tail = locator
    return f"$.outputs[{output}].{branch}.options[{option}].slots[{slot}].tails[{tail}]"


def _uses_pua(tail: Mapping[str, Any]) -> bool:
    return tail.get("pua_base") not in (None, "") or bool(tail.get("glyph_map"))


def scan_needs_trusted_tail_profile_proof(scan: Mapping[str, Any]) -> bool:
    """Whether this scan asserts a usable automatic OpenType/PUA tail rule."""

    return any(
        str(tail.get("tail_profile_status") or "") == "auto" and _uses_tail_profile(tail)
        for _, tail in iter_contract_tails(scan)
    )


def automatic_tail_profile_coverage_issues(scan: Mapping[str, Any]) -> list[dict[str, str]]:
    """Require the scanner's explicit full-alphabet result before it is signed."""

    issues: list[dict[str, str]] = []
    for locator, tail in iter_contract_tails(scan):
        if str(tail.get("tail_profile_status") or "") != "auto" or not _uses_tail_profile(tail):
            continue
        coverage = tail.get("tail_profile_coverage")
        if _has_full_coverage(tail):
            continue
        issues.append({
            "path": tail_path(locator),
            "code": "tail_profile_coverage_missing",
            "reason": "自动尾巴字形缺少完整 a-z 覆盖扫描结果；请使用新版客户端重新扫描模板。",
        })
    return issues


def _matches_auto_tail_scan(configured: Mapping[str, Any], scanned: Mapping[str, Any] | None) -> bool:
    if not isinstance(scanned, Mapping) or str(scanned.get("tail_profile_status") or "") != "auto":
        return False
    for key in ("key", "position", "sample"):
        if str(configured.get(key) or "") != str(scanned.get(key) or ""):
            return False
    return (
        configured.get("pua_base") == scanned.get("pua_base")
        and _glyph_map(configured.get("glyph_map")) == _glyph_map(scanned.get("glyph_map"))
        and str(configured.get("opentype_feature") or "") == str(scanned.get("opentype_feature") or "")
        and configured.get("opentype_alternate_index") == scanned.get("opentype_alternate_index")
    )


def _matches_tail_font_dependency(
    configured_option: Mapping[str, Any],
    configured_slot: Mapping[str, Any],
    scanned: Mapping[str, Any] | None,
) -> bool:
    """Bind a profile to the exact font that the renderer will use.

    Illustrator records the tail marker's own font in the trusted scan. The V2
    renderer resolves its font from the slot first and then the option, so a
    profile is valid only when both sides resolve to the same single font.
    """

    if not isinstance(scanned, Mapping):
        return False
    scanned_fonts = _unique_font_dependencies(scanned.get("font_dependencies"))
    configured_fonts = _effective_font_dependencies(configured_option, configured_slot)
    return (
        len(scanned_fonts) == 1
        and len(configured_fonts) == 1
        and scanned_fonts[0].casefold() == configured_fonts[0].casefold()
    )


def _effective_font_dependencies(option: Mapping[str, Any], slot: Mapping[str, Any]) -> list[str]:
    slot_fonts = _unique_font_dependencies(slot.get("font_dependencies"))
    return slot_fonts or _unique_font_dependencies(option.get("font_dependencies"))


def _unique_font_dependencies(value: Any) -> list[str]:
    result: list[str] = []
    seen: set[str] = set()
    for raw in value if isinstance(value, list) else []:
        name = str(raw or "").strip()
        normalized = name.casefold()
        if name and normalized not in seen:
            result.append(name)
            seen.add(normalized)
    return result


def pua_tail_profile_issues(config: Mapping[str, Any], scan: Mapping[str, Any]) -> list[dict[str, str]]:
    """Compatibility name for callers that originally only guarded PUA tails."""

    return tail_profile_issues(config, scan)


def _uses_tail_profile(tail: Mapping[str, Any]) -> bool:
    return _uses_pua(tail) or (
        str(tail.get("opentype_feature") or "").strip()
        and isinstance(tail.get("opentype_alternate_index"), int)
        and not isinstance(tail.get("opentype_alternate_index"), bool)
    )


def _has_full_coverage(tail: Mapping[str, Any] | None) -> bool:
    coverage = tail.get("tail_profile_coverage") if isinstance(tail, Mapping) else None
    return (
        isinstance(coverage, Mapping)
        and coverage.get("verified") is True
        and str(coverage.get("alphabet") or "") == ASCII_LOWERCASE
        and int(coverage.get("version") or 0) == 1
    )


def _has_trusted_tail_profile_proof(scan: Mapping[str, Any]) -> bool:
    proof = scan.get("tail_profile_proof")
    if not isinstance(proof, Mapping) or int(proof.get("version") or 0) != TAIL_PROFILE_PROOF_VERSION:
        return False
    evidence = dict(scan)
    evidence.pop("tail_profile_proof", None)
    return str(proof.get("evidence_sha256") or "").strip().lower() == scan_evidence_sha256(evidence)


def _glyph_map(value: Any) -> dict[str, Any]:
    return dict(value) if isinstance(value, Mapping) else {}


__all__ = [
    "ASCII_LOWERCASE",
    "TAIL_PROFILE_PROOF_VERSION",
    "TailLocator",
    "automatic_tail_profile_coverage_issues",
    "iter_contract_tails",
    "pua_tail_profile_issues",
    "scan_needs_trusted_tail_profile_proof",
    "tail_profile_issues",
    "tail_path",
]
